# -*- coding: utf-8 -*-
"""Assignment1_DSA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aW4kfA-t7Zd5BF1WMx3Nol6gP3Pw1Wrx

# Discrete Uniform Distribution
### Problem statement
The number of books sold by a bookseller per day is given in 'bookseller.csv'.
Let X = Number of books sold by a bookseller per day
X is a Discrete Random variable (because it represents the book count). Let's see the distribution
of X and answer the below questions.
1. Find the probability that more than (or equal to) 96 books will be sold on a given day
2. Find the probability that less than (or equal to) 92 books will be sold on a given day
"""

import pandas as pd
book=pd.read_csv('bookseller.csv')
book.head()

book.shape

book.describe()

import scipy.stats as stats
import numpy as np
k=np.arange(90,101)
prob=stats.uniform.pdf(k,loc=90,scale=11)
prob

# 1) Find the probability that more than (or equal to) 96 books will be sold on a given day
1-stats.uniform.cdf(96,90,11)

# 2) Find the probability that less than (or equal to) 92 books will be sold on a given day
stats.uniform.cdf(93,90,11)

"""# Continuous Uniform Distribution
### Problem statement
IT industry records the amount of time a software engineer needs to fix a bug in the initial phase
of software development in 'debugging.csv'.
Let X = Time needed to fix bugs
X is a continuous random variable. Let's see the distribution of X and answer the below
questions.
1. Find the probability that a randomly selected software debugging requires less than three
hours
2. Find the probability that a randomly selected software debugging requires more than two
hours
3. Find the 50th percentile of the software debugging time

"""

bug=pd.read_csv('debugging.csv')
bug.head()

bug.describe()

import numpy as np
from scipy.stats import uniform
x=np.linspace(1,5,50)
probs=stats.uniform.pdf(x,1,4)
probs

# 1)Find the probability that a randomly selected software debugging requires less than three hours
stats.uniform.cdf(3,1,4)

# 2)Find the probability that a randomly selected software debugging requires more than two hours
1- stats.uniform.cdf(2,1,4)

# 3)Find the 50th percentile of the software debugging time
uniform.ppf(q=0.25, loc=1, scale=4)