# -*- coding: utf-8 -*-
"""dsa-unit2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cVL7fsTzjjnLNjT1oIDrriIYsR3htkG4
"""

import pandas as pd

# Sample data: House features and prices
data = {'Size (sq ft)': [1500, 1600, 1700, 1800, 1900,1750],
        'Bedrooms': [3, 3, 3, 4, 4,4,],
        'Price ($)': [300000, 320000, 340000, 360000, 380000,375000]}

df = pd.DataFrame(data)
df

"""Simple lr= when only i independent variabke is present and 1 target variable
Multiple lr= when more than 1 independent variabkle and the target variable is present

### Errors-
* Mean Square Error
* Root Mean Square Error
* R Squared Error- values will come in between 0 and 1,1 is best 0 is worst
* Mean Absolute Error
"""

from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score

import pandas as pd
df=pd.read_csv('anime_ratings_data.csv')
df

df.describe()

